### ISSUE TITLE
Mensagens do commit

### ISSUE THREAD

**Issue by gabriel-bandeira** [Carol10/ProjMoveSec#1]
As mensagens dos commit estão muito simples e sem descrição. O ideal é que, além da mensagem curta do commit, também tenha uma descrição mais longa sobre as features que foram implementadas naquele commit. Pra isso, é interessante não utilizar a opção "-m" no comando "git commit", pois ao abrir um editor de texto, o desenvolvedor pode digitar um texto maior explicando todas features desenvolvidas.

**Comment by lra2** [comment]
Ok, daremos um jeito nisso. É que como esses primeiros commits era apenas protótipos sem muitas funções realmente implementadas, acabou que não demos muita importância a isso.
